apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hardware-monitor
  namespace: eagle-eye
spec:
  selector:
    matchLabels:
      app: hardware-monitor
  template:
    metadata:
      labels:
        app: hardware-monitor
    spec:
      serviceAccountName: hardware-monitor-serviceaccount
      initContainers:
        - name: wait-for-nats
          image: {{ .Values.images.init.repository }}:{{ .Values.images.init.tag }}
          command:
            - /bin/sh
            - -c
            - |
              until nc -z nats.nats 4222; do
                echo "Wait NATS service...";
                sleep 3;
              done;
              echo "NATS service is ready!";
        - name: monitor-container
          image: "cr.openfuyao.cn/openfuyao/bitnami/kubectl:1.33"
          command:
            - "sh"
            - "-c"
            - |
              kubectl wait --for=condition=Ready --namespace=eagle-eye pod -l app=hardware-diagnosis
              echo "All resources are ready. Now starting monitor setup."
      containers:
        - name: hardware-monitor
          image: {{ .Values.images.core.repository }}:{{ .Values.images.core.tag }}
          imagePullPolicy: {{ .Values.images.core.pullPolicy }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MODULE_NAME
              value: "hardware-monitor"
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
            runAsUser: 0
            runAsGroup: 0
          ports:
            - name: http
              containerPort: 8537
          volumeMounts:
            - name: log-hardware-monitor
              mountPath: /var/log/hardware-monitor
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: ascend-driver
              mountPath: /usr/local/Ascend/driver
              readOnly: true
            - name: ascend-dcmi
              mountPath: /usr/local/dcmi
              readOnly: true
            - name: containerd
              mountPath: /run/containerd
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: log-hardware-monitor
          hostPath:
            path: /var/log/hardware-monitor
            type: DirectoryOrCreate
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: ascend-driver
          hostPath:
            path: /usr/local/Ascend/driver
        - name: ascend-dcmi
          hostPath:
            path: /usr/local/dcmi
        - name: containerd
          hostPath:
            path: /run/containerd
        - name: tmp
          hostPath:
            path: /tmp