{{- if eq (include "prometheus.installed" .) "false" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-nats-exporter
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ .Release.Name }}-nats-exporter
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
  endpoints:
    - port: metrics
      interval: 10s
      path: /metrics
  namespaceSelector:
    matchNames:
      - nats
{{- end }}