annotations:
  category: AI/Machine Learning
apiVersion: v1
description: Helm chart for deploying LLMInferenceService crds
home: https://kserve.github.io/website/
icon: https://raw.githubusercontent.com/kserve/website/main/docs/images/logo.png
keywords:
- kserve
- llm
- llm-d
- inference
- generative-ai
- machine-learning
- model-serving
maintainers:
- name: KServe Team
  url: https://github.com/kserve/kserve
name: kserve-llmisvc-crd
sources:
- https://github.com/kserve/kserve
version: v0.16.0
