{{- if not .Values.isPDAggregated }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-proxy-sa
  namespace: {{ $.Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vllm-proxy-role
  namespace: {{ $.Values.global.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-proxy-rolebinding
  namespace: {{ $.Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: vllm-proxy-sa
  namespace: {{ $.Values.global.namespace }}
roleRef:
  kind: Role
  name: vllm-proxy-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}