apiVersion: v2
appVersion: 2.8.0
dependencies:
- condition: dra.enabled
  name: hami-dra
  repository: https://project-hami.github.io/HAMi-DRA/
  version: 0.1.0
description: Heterogeneous AI Computing Virtualization Middleware
keywords:
- vgpu
- gpu
kubeVersion: '>= 1.18.0-0'
maintainers:
- email: archlitchi@gmail.com
  name: limengxuan
- email: xiaozhang0210@hotmail.com
  name: zhangxiao
name: hami
sources:
- https://github.com/Project-HAMi/HAMi
type: application
version: 2.8.0
