apiVersion: v1
appVersion: 0.21.1
description: 'hardware-monitor is a component that performs health checks on the hardware
  components of the system, specifically targeting NPU and GPU devices. It collects
  detailed information on device status, memory usage, and hardware errors, which
  can be used for proactive management and troubleshooting of hardware resources. '
keywords:
- artificial-intelligence
name: hardware-monitor
version: 0.21.1
